// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/browseronly.proto

package cloud.lazycat.apis.common;

public final class Browseronly {
  private Browseronly() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface APIServerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cloud.lazycat.apis.common.APIServerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string frontend_version = 1;</code>
     * @return The frontendVersion.
     */
    java.lang.String getFrontendVersion();
    /**
     * <code>string frontend_version = 1;</code>
     * @return The bytes for frontendVersion.
     */
    com.google.protobuf.ByteString
        getFrontendVersionBytes();

    /**
     * <code>string backend_version = 2;</code>
     * @return The backendVersion.
     */
    java.lang.String getBackendVersion();
    /**
     * <code>string backend_version = 2;</code>
     * @return The bytes for backendVersion.
     */
    com.google.protobuf.ByteString
        getBackendVersionBytes();
  }
  /**
   * Protobuf type {@code cloud.lazycat.apis.common.APIServerInfo}
   */
  public static final class APIServerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cloud.lazycat.apis.common.APIServerInfo)
      APIServerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIServerInfo.newBuilder() to construct.
    private APIServerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIServerInfo() {
      frontendVersion_ = "";
      backendVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new APIServerInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIServerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              frontendVersion_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              backendVersion_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_APIServerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.lazycat.apis.common.Browseronly.APIServerInfo.class, cloud.lazycat.apis.common.Browseronly.APIServerInfo.Builder.class);
    }

    public static final int FRONTEND_VERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object frontendVersion_;
    /**
     * <code>string frontend_version = 1;</code>
     * @return The frontendVersion.
     */
    @java.lang.Override
    public java.lang.String getFrontendVersion() {
      java.lang.Object ref = frontendVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        frontendVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string frontend_version = 1;</code>
     * @return The bytes for frontendVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFrontendVersionBytes() {
      java.lang.Object ref = frontendVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frontendVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BACKEND_VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object backendVersion_;
    /**
     * <code>string backend_version = 2;</code>
     * @return The backendVersion.
     */
    @java.lang.Override
    public java.lang.String getBackendVersion() {
      java.lang.Object ref = backendVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backendVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string backend_version = 2;</code>
     * @return The bytes for backendVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBackendVersionBytes() {
      java.lang.Object ref = backendVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backendVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(frontendVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, frontendVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backendVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, backendVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(frontendVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, frontendVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backendVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, backendVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cloud.lazycat.apis.common.Browseronly.APIServerInfo)) {
        return super.equals(obj);
      }
      cloud.lazycat.apis.common.Browseronly.APIServerInfo other = (cloud.lazycat.apis.common.Browseronly.APIServerInfo) obj;

      if (!getFrontendVersion()
          .equals(other.getFrontendVersion())) return false;
      if (!getBackendVersion()
          .equals(other.getBackendVersion())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FRONTEND_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFrontendVersion().hashCode();
      hash = (37 * hash) + BACKEND_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getBackendVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cloud.lazycat.apis.common.Browseronly.APIServerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cloud.lazycat.apis.common.APIServerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cloud.lazycat.apis.common.APIServerInfo)
        cloud.lazycat.apis.common.Browseronly.APIServerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_APIServerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cloud.lazycat.apis.common.Browseronly.APIServerInfo.class, cloud.lazycat.apis.common.Browseronly.APIServerInfo.Builder.class);
      }

      // Construct using cloud.lazycat.apis.common.Browseronly.APIServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        frontendVersion_ = "";

        backendVersion_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.APIServerInfo getDefaultInstanceForType() {
        return cloud.lazycat.apis.common.Browseronly.APIServerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.APIServerInfo build() {
        cloud.lazycat.apis.common.Browseronly.APIServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.APIServerInfo buildPartial() {
        cloud.lazycat.apis.common.Browseronly.APIServerInfo result = new cloud.lazycat.apis.common.Browseronly.APIServerInfo(this);
        result.frontendVersion_ = frontendVersion_;
        result.backendVersion_ = backendVersion_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cloud.lazycat.apis.common.Browseronly.APIServerInfo) {
          return mergeFrom((cloud.lazycat.apis.common.Browseronly.APIServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cloud.lazycat.apis.common.Browseronly.APIServerInfo other) {
        if (other == cloud.lazycat.apis.common.Browseronly.APIServerInfo.getDefaultInstance()) return this;
        if (!other.getFrontendVersion().isEmpty()) {
          frontendVersion_ = other.frontendVersion_;
          onChanged();
        }
        if (!other.getBackendVersion().isEmpty()) {
          backendVersion_ = other.backendVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cloud.lazycat.apis.common.Browseronly.APIServerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cloud.lazycat.apis.common.Browseronly.APIServerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object frontendVersion_ = "";
      /**
       * <code>string frontend_version = 1;</code>
       * @return The frontendVersion.
       */
      public java.lang.String getFrontendVersion() {
        java.lang.Object ref = frontendVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          frontendVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string frontend_version = 1;</code>
       * @return The bytes for frontendVersion.
       */
      public com.google.protobuf.ByteString
          getFrontendVersionBytes() {
        java.lang.Object ref = frontendVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          frontendVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string frontend_version = 1;</code>
       * @param value The frontendVersion to set.
       * @return This builder for chaining.
       */
      public Builder setFrontendVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        frontendVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string frontend_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrontendVersion() {
        
        frontendVersion_ = getDefaultInstance().getFrontendVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string frontend_version = 1;</code>
       * @param value The bytes for frontendVersion to set.
       * @return This builder for chaining.
       */
      public Builder setFrontendVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        frontendVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object backendVersion_ = "";
      /**
       * <code>string backend_version = 2;</code>
       * @return The backendVersion.
       */
      public java.lang.String getBackendVersion() {
        java.lang.Object ref = backendVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          backendVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string backend_version = 2;</code>
       * @return The bytes for backendVersion.
       */
      public com.google.protobuf.ByteString
          getBackendVersionBytes() {
        java.lang.Object ref = backendVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          backendVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string backend_version = 2;</code>
       * @param value The backendVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBackendVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        backendVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string backend_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBackendVersion() {
        
        backendVersion_ = getDefaultInstance().getBackendVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string backend_version = 2;</code>
       * @param value The bytes for backendVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBackendVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        backendVersion_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cloud.lazycat.apis.common.APIServerInfo)
    }

    // @@protoc_insertion_point(class_scope:cloud.lazycat.apis.common.APIServerInfo)
    private static final cloud.lazycat.apis.common.Browseronly.APIServerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cloud.lazycat.apis.common.Browseronly.APIServerInfo();
    }

    public static cloud.lazycat.apis.common.Browseronly.APIServerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIServerInfo>
        PARSER = new com.google.protobuf.AbstractParser<APIServerInfo>() {
      @java.lang.Override
      public APIServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIServerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIServerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIServerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cloud.lazycat.apis.common.Browseronly.APIServerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SessionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cloud.lazycat.apis.common.SessionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前登陆用户
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 当前登陆用户
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     * 当前登陆设备
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <pre>
     * 当前登陆设备
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     * @return Whether the when field is set.
     */
    boolean hasWhen();
    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     * @return The when.
     */
    com.google.protobuf.Timestamp getWhen();
    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWhenOrBuilder();
  }
  /**
   * Protobuf type {@code cloud.lazycat.apis.common.SessionInfo}
   */
  public static final class SessionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cloud.lazycat.apis.common.SessionInfo)
      SessionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SessionInfo.newBuilder() to construct.
    private SessionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SessionInfo() {
      uid_ = "";
      deviceId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SessionInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SessionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (when_ != null) {
                subBuilder = when_.toBuilder();
              }
              when_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(when_);
                when_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_SessionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.lazycat.apis.common.Browseronly.SessionInfo.class, cloud.lazycat.apis.common.Browseronly.SessionInfo.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 当前登陆用户
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前登陆用户
     * </pre>
     *
     * <code>string uid = 1;</code>
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceId_;
    /**
     * <pre>
     * 当前登陆设备
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 当前登陆设备
     * </pre>
     *
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WHEN_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp when_;
    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     * @return Whether the when field is set.
     */
    @java.lang.Override
    public boolean hasWhen() {
      return when_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     * @return The when.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWhen() {
      return when_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : when_;
    }
    /**
     * <code>.google.protobuf.Timestamp when = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWhenOrBuilder() {
      return getWhen();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
      }
      if (when_ != null) {
        output.writeMessage(3, getWhen());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
      }
      if (when_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWhen());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cloud.lazycat.apis.common.Browseronly.SessionInfo)) {
        return super.equals(obj);
      }
      cloud.lazycat.apis.common.Browseronly.SessionInfo other = (cloud.lazycat.apis.common.Browseronly.SessionInfo) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (hasWhen() != other.hasWhen()) return false;
      if (hasWhen()) {
        if (!getWhen()
            .equals(other.getWhen())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      if (hasWhen()) {
        hash = (37 * hash) + WHEN_FIELD_NUMBER;
        hash = (53 * hash) + getWhen().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.SessionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cloud.lazycat.apis.common.Browseronly.SessionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cloud.lazycat.apis.common.SessionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cloud.lazycat.apis.common.SessionInfo)
        cloud.lazycat.apis.common.Browseronly.SessionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_SessionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cloud.lazycat.apis.common.Browseronly.SessionInfo.class, cloud.lazycat.apis.common.Browseronly.SessionInfo.Builder.class);
      }

      // Construct using cloud.lazycat.apis.common.Browseronly.SessionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        deviceId_ = "";

        if (whenBuilder_ == null) {
          when_ = null;
        } else {
          when_ = null;
          whenBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.SessionInfo getDefaultInstanceForType() {
        return cloud.lazycat.apis.common.Browseronly.SessionInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.SessionInfo build() {
        cloud.lazycat.apis.common.Browseronly.SessionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.SessionInfo buildPartial() {
        cloud.lazycat.apis.common.Browseronly.SessionInfo result = new cloud.lazycat.apis.common.Browseronly.SessionInfo(this);
        result.uid_ = uid_;
        result.deviceId_ = deviceId_;
        if (whenBuilder_ == null) {
          result.when_ = when_;
        } else {
          result.when_ = whenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cloud.lazycat.apis.common.Browseronly.SessionInfo) {
          return mergeFrom((cloud.lazycat.apis.common.Browseronly.SessionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cloud.lazycat.apis.common.Browseronly.SessionInfo other) {
        if (other == cloud.lazycat.apis.common.Browseronly.SessionInfo.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasWhen()) {
          mergeWhen(other.getWhen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cloud.lazycat.apis.common.Browseronly.SessionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cloud.lazycat.apis.common.Browseronly.SessionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 当前登陆用户
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 当前登陆用户
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前登陆用户
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前登陆用户
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前登陆用户
       * </pre>
       *
       * <code>string uid = 1;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <pre>
       * 当前登陆设备
       * </pre>
       *
       * <code>string device_id = 2;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 当前登陆设备
       * </pre>
       *
       * <code>string device_id = 2;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 当前登陆设备
       * </pre>
       *
       * <code>string device_id = 2;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前登陆设备
       * </pre>
       *
       * <code>string device_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前登陆设备
       * </pre>
       *
       * <code>string device_id = 2;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp when_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> whenBuilder_;
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       * @return Whether the when field is set.
       */
      public boolean hasWhen() {
        return whenBuilder_ != null || when_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       * @return The when.
       */
      public com.google.protobuf.Timestamp getWhen() {
        if (whenBuilder_ == null) {
          return when_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : when_;
        } else {
          return whenBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public Builder setWhen(com.google.protobuf.Timestamp value) {
        if (whenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          when_ = value;
          onChanged();
        } else {
          whenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public Builder setWhen(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (whenBuilder_ == null) {
          when_ = builderForValue.build();
          onChanged();
        } else {
          whenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public Builder mergeWhen(com.google.protobuf.Timestamp value) {
        if (whenBuilder_ == null) {
          if (when_ != null) {
            when_ =
              com.google.protobuf.Timestamp.newBuilder(when_).mergeFrom(value).buildPartial();
          } else {
            when_ = value;
          }
          onChanged();
        } else {
          whenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public Builder clearWhen() {
        if (whenBuilder_ == null) {
          when_ = null;
          onChanged();
        } else {
          when_ = null;
          whenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWhenBuilder() {
        
        onChanged();
        return getWhenFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWhenOrBuilder() {
        if (whenBuilder_ != null) {
          return whenBuilder_.getMessageOrBuilder();
        } else {
          return when_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : when_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp when = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWhenFieldBuilder() {
        if (whenBuilder_ == null) {
          whenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWhen(),
                  getParentForChildren(),
                  isClean());
          when_ = null;
        }
        return whenBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cloud.lazycat.apis.common.SessionInfo)
    }

    // @@protoc_insertion_point(class_scope:cloud.lazycat.apis.common.SessionInfo)
    private static final cloud.lazycat.apis.common.Browseronly.SessionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cloud.lazycat.apis.common.Browseronly.SessionInfo();
    }

    public static cloud.lazycat.apis.common.Browseronly.SessionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SessionInfo>
        PARSER = new com.google.protobuf.AbstractParser<SessionInfo>() {
      @java.lang.Override
      public SessionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SessionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SessionInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cloud.lazycat.apis.common.Browseronly.SessionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cloud.lazycat.apis.common.AppInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string box_id = 1;</code>
     * @return The boxId.
     */
    java.lang.String getBoxId();
    /**
     * <code>string box_id = 1;</code>
     * @return The bytes for boxId.
     */
    com.google.protobuf.ByteString
        getBoxIdBytes();

    /**
     * <code>string app_id = 2;</code>
     * @return The appId.
     */
    java.lang.String getAppId();
    /**
     * <code>string app_id = 2;</code>
     * @return The bytes for appId.
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string app_domain = 3;</code>
     * @return The appDomain.
     */
    java.lang.String getAppDomain();
    /**
     * <code>string app_domain = 3;</code>
     * @return The bytes for appDomain.
     */
    com.google.protobuf.ByteString
        getAppDomainBytes();

    /**
     * <pre>
     * APIGateway对所有而http service服务强制要求设置http header类型的
     * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
     * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
     * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
     * 参数调整。
     * </pre>
     *
     * <code>string http_api_proxy_path = 4;</code>
     * @return The httpApiProxyPath.
     */
    java.lang.String getHttpApiProxyPath();
    /**
     * <pre>
     * APIGateway对所有而http service服务强制要求设置http header类型的
     * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
     * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
     * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
     * 参数调整。
     * </pre>
     *
     * <code>string http_api_proxy_path = 4;</code>
     * @return The bytes for httpApiProxyPath.
     */
    com.google.protobuf.ByteString
        getHttpApiProxyPathBytes();
  }
  /**
   * Protobuf type {@code cloud.lazycat.apis.common.AppInfo}
   */
  public static final class AppInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cloud.lazycat.apis.common.AppInfo)
      AppInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppInfo.newBuilder() to construct.
    private AppInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppInfo() {
      boxId_ = "";
      appId_ = "";
      appDomain_ = "";
      httpApiProxyPath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              boxId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appDomain_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              httpApiProxyPath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_AppInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_AppInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.lazycat.apis.common.Browseronly.AppInfo.class, cloud.lazycat.apis.common.Browseronly.AppInfo.Builder.class);
    }

    public static final int BOX_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object boxId_;
    /**
     * <code>string box_id = 1;</code>
     * @return The boxId.
     */
    @java.lang.Override
    public java.lang.String getBoxId() {
      java.lang.Object ref = boxId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boxId_ = s;
        return s;
      }
    }
    /**
     * <code>string box_id = 1;</code>
     * @return The bytes for boxId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBoxIdBytes() {
      java.lang.Object ref = boxId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boxId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object appId_;
    /**
     * <code>string app_id = 2;</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string app_id = 2;</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_DOMAIN_FIELD_NUMBER = 3;
    private volatile java.lang.Object appDomain_;
    /**
     * <code>string app_domain = 3;</code>
     * @return The appDomain.
     */
    @java.lang.Override
    public java.lang.String getAppDomain() {
      java.lang.Object ref = appDomain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appDomain_ = s;
        return s;
      }
    }
    /**
     * <code>string app_domain = 3;</code>
     * @return The bytes for appDomain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppDomainBytes() {
      java.lang.Object ref = appDomain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appDomain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTP_API_PROXY_PATH_FIELD_NUMBER = 4;
    private volatile java.lang.Object httpApiProxyPath_;
    /**
     * <pre>
     * APIGateway对所有而http service服务强制要求设置http header类型的
     * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
     * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
     * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
     * 参数调整。
     * </pre>
     *
     * <code>string http_api_proxy_path = 4;</code>
     * @return The httpApiProxyPath.
     */
    @java.lang.Override
    public java.lang.String getHttpApiProxyPath() {
      java.lang.Object ref = httpApiProxyPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpApiProxyPath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * APIGateway对所有而http service服务强制要求设置http header类型的
     * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
     * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
     * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
     * 参数调整。
     * </pre>
     *
     * <code>string http_api_proxy_path = 4;</code>
     * @return The bytes for httpApiProxyPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHttpApiProxyPathBytes() {
      java.lang.Object ref = httpApiProxyPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpApiProxyPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(boxId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, boxId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appDomain_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appDomain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(httpApiProxyPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, httpApiProxyPath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(boxId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, boxId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appDomain_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appDomain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(httpApiProxyPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, httpApiProxyPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cloud.lazycat.apis.common.Browseronly.AppInfo)) {
        return super.equals(obj);
      }
      cloud.lazycat.apis.common.Browseronly.AppInfo other = (cloud.lazycat.apis.common.Browseronly.AppInfo) obj;

      if (!getBoxId()
          .equals(other.getBoxId())) return false;
      if (!getAppId()
          .equals(other.getAppId())) return false;
      if (!getAppDomain()
          .equals(other.getAppDomain())) return false;
      if (!getHttpApiProxyPath()
          .equals(other.getHttpApiProxyPath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOX_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBoxId().hashCode();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + APP_DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getAppDomain().hashCode();
      hash = (37 * hash) + HTTP_API_PROXY_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getHttpApiProxyPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cloud.lazycat.apis.common.Browseronly.AppInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cloud.lazycat.apis.common.Browseronly.AppInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cloud.lazycat.apis.common.AppInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cloud.lazycat.apis.common.AppInfo)
        cloud.lazycat.apis.common.Browseronly.AppInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_AppInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_AppInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cloud.lazycat.apis.common.Browseronly.AppInfo.class, cloud.lazycat.apis.common.Browseronly.AppInfo.Builder.class);
      }

      // Construct using cloud.lazycat.apis.common.Browseronly.AppInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        boxId_ = "";

        appId_ = "";

        appDomain_ = "";

        httpApiProxyPath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cloud.lazycat.apis.common.Browseronly.internal_static_cloud_lazycat_apis_common_AppInfo_descriptor;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.AppInfo getDefaultInstanceForType() {
        return cloud.lazycat.apis.common.Browseronly.AppInfo.getDefaultInstance();
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.AppInfo build() {
        cloud.lazycat.apis.common.Browseronly.AppInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cloud.lazycat.apis.common.Browseronly.AppInfo buildPartial() {
        cloud.lazycat.apis.common.Browseronly.AppInfo result = new cloud.lazycat.apis.common.Browseronly.AppInfo(this);
        result.boxId_ = boxId_;
        result.appId_ = appId_;
        result.appDomain_ = appDomain_;
        result.httpApiProxyPath_ = httpApiProxyPath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cloud.lazycat.apis.common.Browseronly.AppInfo) {
          return mergeFrom((cloud.lazycat.apis.common.Browseronly.AppInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cloud.lazycat.apis.common.Browseronly.AppInfo other) {
        if (other == cloud.lazycat.apis.common.Browseronly.AppInfo.getDefaultInstance()) return this;
        if (!other.getBoxId().isEmpty()) {
          boxId_ = other.boxId_;
          onChanged();
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getAppDomain().isEmpty()) {
          appDomain_ = other.appDomain_;
          onChanged();
        }
        if (!other.getHttpApiProxyPath().isEmpty()) {
          httpApiProxyPath_ = other.httpApiProxyPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cloud.lazycat.apis.common.Browseronly.AppInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cloud.lazycat.apis.common.Browseronly.AppInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object boxId_ = "";
      /**
       * <code>string box_id = 1;</code>
       * @return The boxId.
       */
      public java.lang.String getBoxId() {
        java.lang.Object ref = boxId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          boxId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string box_id = 1;</code>
       * @return The bytes for boxId.
       */
      public com.google.protobuf.ByteString
          getBoxIdBytes() {
        java.lang.Object ref = boxId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          boxId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string box_id = 1;</code>
       * @param value The boxId to set.
       * @return This builder for chaining.
       */
      public Builder setBoxId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        boxId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string box_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoxId() {
        
        boxId_ = getDefaultInstance().getBoxId();
        onChanged();
        return this;
      }
      /**
       * <code>string box_id = 1;</code>
       * @param value The bytes for boxId to set.
       * @return This builder for chaining.
       */
      public Builder setBoxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        boxId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string app_id = 2;</code>
       * @return The appId.
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_id = 2;</code>
       * @return The bytes for appId.
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_id = 2;</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string app_id = 2;</code>
       * @param value The bytes for appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appDomain_ = "";
      /**
       * <code>string app_domain = 3;</code>
       * @return The appDomain.
       */
      public java.lang.String getAppDomain() {
        java.lang.Object ref = appDomain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appDomain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_domain = 3;</code>
       * @return The bytes for appDomain.
       */
      public com.google.protobuf.ByteString
          getAppDomainBytes() {
        java.lang.Object ref = appDomain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appDomain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_domain = 3;</code>
       * @param value The appDomain to set.
       * @return This builder for chaining.
       */
      public Builder setAppDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appDomain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_domain = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppDomain() {
        
        appDomain_ = getDefaultInstance().getAppDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string app_domain = 3;</code>
       * @param value The bytes for appDomain to set.
       * @return This builder for chaining.
       */
      public Builder setAppDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appDomain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object httpApiProxyPath_ = "";
      /**
       * <pre>
       * APIGateway对所有而http service服务强制要求设置http header类型的
       * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
       * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
       * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
       * 参数调整。
       * </pre>
       *
       * <code>string http_api_proxy_path = 4;</code>
       * @return The httpApiProxyPath.
       */
      public java.lang.String getHttpApiProxyPath() {
        java.lang.Object ref = httpApiProxyPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          httpApiProxyPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * APIGateway对所有而http service服务强制要求设置http header类型的
       * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
       * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
       * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
       * 参数调整。
       * </pre>
       *
       * <code>string http_api_proxy_path = 4;</code>
       * @return The bytes for httpApiProxyPath.
       */
      public com.google.protobuf.ByteString
          getHttpApiProxyPathBytes() {
        java.lang.Object ref = httpApiProxyPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpApiProxyPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * APIGateway对所有而http service服务强制要求设置http header类型的
       * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
       * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
       * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
       * 参数调整。
       * </pre>
       *
       * <code>string http_api_proxy_path = 4;</code>
       * @param value The httpApiProxyPath to set.
       * @return This builder for chaining.
       */
      public Builder setHttpApiProxyPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        httpApiProxyPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APIGateway对所有而http service服务强制要求设置http header类型的
       * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
       * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
       * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
       * 参数调整。
       * </pre>
       *
       * <code>string http_api_proxy_path = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHttpApiProxyPath() {
        
        httpApiProxyPath_ = getDefaultInstance().getHttpApiProxyPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APIGateway对所有而http service服务强制要求设置http header类型的
       * AuthInfo. 但有些场景无法使用XHR去设置自定义的http header，导致访问
       * 这些服务很困难，因此由/usr/bin/lzcapp统一提供一个代理服务来设置这个
       * header. 此字段即是对应代理出来的URL前缀。默认为"/_lzc"，可以通过启动
       * 参数调整。
       * </pre>
       *
       * <code>string http_api_proxy_path = 4;</code>
       * @param value The bytes for httpApiProxyPath to set.
       * @return This builder for chaining.
       */
      public Builder setHttpApiProxyPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        httpApiProxyPath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cloud.lazycat.apis.common.AppInfo)
    }

    // @@protoc_insertion_point(class_scope:cloud.lazycat.apis.common.AppInfo)
    private static final cloud.lazycat.apis.common.Browseronly.AppInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cloud.lazycat.apis.common.Browseronly.AppInfo();
    }

    public static cloud.lazycat.apis.common.Browseronly.AppInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppInfo>
        PARSER = new com.google.protobuf.AbstractParser<AppInfo>() {
      @java.lang.Override
      public AppInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cloud.lazycat.apis.common.Browseronly.AppInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_lazycat_apis_common_APIServerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_lazycat_apis_common_SessionInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cloud_lazycat_apis_common_AppInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cloud_lazycat_apis_common_AppInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030common/browseronly.proto\022\031cloud.lazyca" +
      "t.apis.common\032\033google/protobuf/empty.pro" +
      "to\032\037google/protobuf/timestamp.proto\"B\n\rA" +
      "PIServerInfo\022\030\n\020frontend_version\030\001 \001(\t\022\027" +
      "\n\017backend_version\030\002 \001(\t\"W\n\013SessionInfo\022\013" +
      "\n\003uid\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022(\n\004when\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\"Z\n\007AppI" +
      "nfo\022\016\n\006box_id\030\001 \001(\t\022\016\n\006app_id\030\002 \001(\t\022\022\n\na" +
      "pp_domain\030\003 \001(\t\022\033\n\023http_api_proxy_path\030\004" +
      " \001(\t2\326\002\n\020BrowserOnlyProxy\022T\n\020QuerySessio" +
      "nInfo\022\026.google.protobuf.Empty\032&.cloud.la" +
      "zycat.apis.common.SessionInfo\"\000\022L\n\014Query" +
      "AppInfo\022\026.google.protobuf.Empty\032\".cloud." +
      "lazycat.apis.common.AppInfo\"\000\022D\n\016PairAll" +
      "Devices\022\026.google.protobuf.Empty\032\026.google" +
      ".protobuf.Empty\"\0000\001\022X\n\022QueryAPIServerInf" +
      "o\022\026.google.protobuf.Empty\032(.cloud.lazyca" +
      "t.apis.common.APIServerInfo\"\000B+Z)gitee.c" +
      "om/linakesi/lzc-sdk/lang/go/commonb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cloud_lazycat_apis_common_APIServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_lazycat_apis_common_APIServerInfo_descriptor,
        new java.lang.String[] { "FrontendVersion", "BackendVersion", });
    internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cloud_lazycat_apis_common_SessionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_lazycat_apis_common_SessionInfo_descriptor,
        new java.lang.String[] { "Uid", "DeviceId", "When", });
    internal_static_cloud_lazycat_apis_common_AppInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cloud_lazycat_apis_common_AppInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cloud_lazycat_apis_common_AppInfo_descriptor,
        new java.lang.String[] { "BoxId", "AppId", "AppDomain", "HttpApiProxyPath", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
