// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: common/end_device.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EndDeviceService_ListEndDevices_FullMethodName  = "/cloud.lazycat.apis.common.EndDeviceService/ListEndDevices"
	EndDeviceService_RemoveEndDevice_FullMethodName = "/cloud.lazycat.apis.common.EndDeviceService/RemoveEndDevice"
)

// EndDeviceServiceClient is the client API for EndDeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndDeviceServiceClient interface {
	// 枚举当前登陆用户所有的设备信息
	ListEndDevices(ctx context.Context, in *ListEndDeviceRequest, opts ...grpc.CallOption) (*ListEndDeviceReply, error)
	// 移除指定uid下面的指定设备(如果设备id为空，将会移除所有的设备）
	RemoveEndDevice(ctx context.Context, in *RemoveEndDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type endDeviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEndDeviceServiceClient(cc grpc.ClientConnInterface) EndDeviceServiceClient {
	return &endDeviceServiceClient{cc}
}

func (c *endDeviceServiceClient) ListEndDevices(ctx context.Context, in *ListEndDeviceRequest, opts ...grpc.CallOption) (*ListEndDeviceReply, error) {
	out := new(ListEndDeviceReply)
	err := c.cc.Invoke(ctx, EndDeviceService_ListEndDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endDeviceServiceClient) RemoveEndDevice(ctx context.Context, in *RemoveEndDeviceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EndDeviceService_RemoveEndDevice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndDeviceServiceServer is the server API for EndDeviceService service.
// All implementations must embed UnimplementedEndDeviceServiceServer
// for forward compatibility
type EndDeviceServiceServer interface {
	// 枚举当前登陆用户所有的设备信息
	ListEndDevices(context.Context, *ListEndDeviceRequest) (*ListEndDeviceReply, error)
	// 移除指定uid下面的指定设备(如果设备id为空，将会移除所有的设备）
	RemoveEndDevice(context.Context, *RemoveEndDeviceRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedEndDeviceServiceServer()
}

// UnimplementedEndDeviceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEndDeviceServiceServer struct {
}

func (UnimplementedEndDeviceServiceServer) ListEndDevices(context.Context, *ListEndDeviceRequest) (*ListEndDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndDevices not implemented")
}
func (UnimplementedEndDeviceServiceServer) RemoveEndDevice(context.Context, *RemoveEndDeviceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEndDevice not implemented")
}
func (UnimplementedEndDeviceServiceServer) mustEmbedUnimplementedEndDeviceServiceServer() {}

// UnsafeEndDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndDeviceServiceServer will
// result in compilation errors.
type UnsafeEndDeviceServiceServer interface {
	mustEmbedUnimplementedEndDeviceServiceServer()
}

func RegisterEndDeviceServiceServer(s grpc.ServiceRegistrar, srv EndDeviceServiceServer) {
	s.RegisterService(&EndDeviceService_ServiceDesc, srv)
}

func _EndDeviceService_ListEndDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceServiceServer).ListEndDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndDeviceService_ListEndDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceServiceServer).ListEndDevices(ctx, req.(*ListEndDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndDeviceService_RemoveEndDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEndDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndDeviceServiceServer).RemoveEndDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EndDeviceService_RemoveEndDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndDeviceServiceServer).RemoveEndDevice(ctx, req.(*RemoveEndDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EndDeviceService_ServiceDesc is the grpc.ServiceDesc for EndDeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EndDeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.lazycat.apis.common.EndDeviceService",
	HandlerType: (*EndDeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndDevices",
			Handler:    _EndDeviceService_ListEndDevices_Handler,
		},
		{
			MethodName: "RemoveEndDevice",
			Handler:    _EndDeviceService_RemoveEndDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/end_device.proto",
}
