// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: common/media_meta.proto

// lzc-thumbnail 中会通过 /run/lzc-sys/lzc-thumbnail.sock 提供以下服务
// - MediaMeta 提供视频或者图片的 metadata 信息
// - Thumbnail 生成视频或者缩略图，目前不支持指定输出的格式和位置。生成的缩略图只可以通过 thumbnail gateway 的方式访问

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MediaMeta_GetUserMediaMeta_FullMethodName      = "/cloud.lazycat.apis.common.MediaMeta/GetUserMediaMeta"
	MediaMeta_GetUserMediaMetaBatch_FullMethodName = "/cloud.lazycat.apis.common.MediaMeta/GetUserMediaMetaBatch"
)

// MediaMetaClient is the client API for MediaMeta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaMetaClient interface {
	GetUserMediaMeta(ctx context.Context, in *GetUserMediaMetaRequest, opts ...grpc.CallOption) (*GetUserMediaMetaResponse, error)
	GetUserMediaMetaBatch(ctx context.Context, opts ...grpc.CallOption) (MediaMeta_GetUserMediaMetaBatchClient, error)
}

type mediaMetaClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaMetaClient(cc grpc.ClientConnInterface) MediaMetaClient {
	return &mediaMetaClient{cc}
}

func (c *mediaMetaClient) GetUserMediaMeta(ctx context.Context, in *GetUserMediaMetaRequest, opts ...grpc.CallOption) (*GetUserMediaMetaResponse, error) {
	out := new(GetUserMediaMetaResponse)
	err := c.cc.Invoke(ctx, MediaMeta_GetUserMediaMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaMetaClient) GetUserMediaMetaBatch(ctx context.Context, opts ...grpc.CallOption) (MediaMeta_GetUserMediaMetaBatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &MediaMeta_ServiceDesc.Streams[0], MediaMeta_GetUserMediaMetaBatch_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &mediaMetaGetUserMediaMetaBatchClient{stream}
	return x, nil
}

type MediaMeta_GetUserMediaMetaBatchClient interface {
	Send(*GetUserMediaMetaRequest) error
	Recv() (*GetUserMediaMetaResponse, error)
	grpc.ClientStream
}

type mediaMetaGetUserMediaMetaBatchClient struct {
	grpc.ClientStream
}

func (x *mediaMetaGetUserMediaMetaBatchClient) Send(m *GetUserMediaMetaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mediaMetaGetUserMediaMetaBatchClient) Recv() (*GetUserMediaMetaResponse, error) {
	m := new(GetUserMediaMetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MediaMetaServer is the server API for MediaMeta service.
// All implementations must embed UnimplementedMediaMetaServer
// for forward compatibility
type MediaMetaServer interface {
	GetUserMediaMeta(context.Context, *GetUserMediaMetaRequest) (*GetUserMediaMetaResponse, error)
	GetUserMediaMetaBatch(MediaMeta_GetUserMediaMetaBatchServer) error
	mustEmbedUnimplementedMediaMetaServer()
}

// UnimplementedMediaMetaServer must be embedded to have forward compatible implementations.
type UnimplementedMediaMetaServer struct {
}

func (UnimplementedMediaMetaServer) GetUserMediaMeta(context.Context, *GetUserMediaMetaRequest) (*GetUserMediaMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMediaMeta not implemented")
}
func (UnimplementedMediaMetaServer) GetUserMediaMetaBatch(MediaMeta_GetUserMediaMetaBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUserMediaMetaBatch not implemented")
}
func (UnimplementedMediaMetaServer) mustEmbedUnimplementedMediaMetaServer() {}

// UnsafeMediaMetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaMetaServer will
// result in compilation errors.
type UnsafeMediaMetaServer interface {
	mustEmbedUnimplementedMediaMetaServer()
}

func RegisterMediaMetaServer(s grpc.ServiceRegistrar, srv MediaMetaServer) {
	s.RegisterService(&MediaMeta_ServiceDesc, srv)
}

func _MediaMeta_GetUserMediaMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMediaMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaMetaServer).GetUserMediaMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaMeta_GetUserMediaMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaMetaServer).GetUserMediaMeta(ctx, req.(*GetUserMediaMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaMeta_GetUserMediaMetaBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaMetaServer).GetUserMediaMetaBatch(&mediaMetaGetUserMediaMetaBatchServer{stream})
}

type MediaMeta_GetUserMediaMetaBatchServer interface {
	Send(*GetUserMediaMetaResponse) error
	Recv() (*GetUserMediaMetaRequest, error)
	grpc.ServerStream
}

type mediaMetaGetUserMediaMetaBatchServer struct {
	grpc.ServerStream
}

func (x *mediaMetaGetUserMediaMetaBatchServer) Send(m *GetUserMediaMetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mediaMetaGetUserMediaMetaBatchServer) Recv() (*GetUserMediaMetaRequest, error) {
	m := new(GetUserMediaMetaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MediaMeta_ServiceDesc is the grpc.ServiceDesc for MediaMeta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaMeta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.lazycat.apis.common.MediaMeta",
	HandlerType: (*MediaMetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserMediaMeta",
			Handler:    _MediaMeta_GetUserMediaMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserMediaMetaBatch",
			Handler:       _MediaMeta_GetUserMediaMetaBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "common/media_meta.proto",
}

const (
	Thumbnail_GenerateFileThumbnail_FullMethodName = "/cloud.lazycat.apis.common.Thumbnail/GenerateFileThumbnail"
	Thumbnail_CleanAll_FullMethodName              = "/cloud.lazycat.apis.common.Thumbnail/CleanAll"
)

// ThumbnailClient is the client API for Thumbnail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbnailClient interface {
	GenerateFileThumbnail(ctx context.Context, in *GenerateFileThumbnailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 清理所有已生成的缩略图
	CleanAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type thumbnailClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbnailClient(cc grpc.ClientConnInterface) ThumbnailClient {
	return &thumbnailClient{cc}
}

func (c *thumbnailClient) GenerateFileThumbnail(ctx context.Context, in *GenerateFileThumbnailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Thumbnail_GenerateFileThumbnail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thumbnailClient) CleanAll(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Thumbnail_CleanAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbnailServer is the server API for Thumbnail service.
// All implementations must embed UnimplementedThumbnailServer
// for forward compatibility
type ThumbnailServer interface {
	GenerateFileThumbnail(context.Context, *GenerateFileThumbnailRequest) (*emptypb.Empty, error)
	// 清理所有已生成的缩略图
	CleanAll(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedThumbnailServer()
}

// UnimplementedThumbnailServer must be embedded to have forward compatible implementations.
type UnimplementedThumbnailServer struct {
}

func (UnimplementedThumbnailServer) GenerateFileThumbnail(context.Context, *GenerateFileThumbnailRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateFileThumbnail not implemented")
}
func (UnimplementedThumbnailServer) CleanAll(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanAll not implemented")
}
func (UnimplementedThumbnailServer) mustEmbedUnimplementedThumbnailServer() {}

// UnsafeThumbnailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbnailServer will
// result in compilation errors.
type UnsafeThumbnailServer interface {
	mustEmbedUnimplementedThumbnailServer()
}

func RegisterThumbnailServer(s grpc.ServiceRegistrar, srv ThumbnailServer) {
	s.RegisterService(&Thumbnail_ServiceDesc, srv)
}

func _Thumbnail_GenerateFileThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFileThumbnailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbnailServer).GenerateFileThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Thumbnail_GenerateFileThumbnail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbnailServer).GenerateFileThumbnail(ctx, req.(*GenerateFileThumbnailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thumbnail_CleanAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbnailServer).CleanAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Thumbnail_CleanAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbnailServer).CleanAll(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Thumbnail_ServiceDesc is the grpc.ServiceDesc for Thumbnail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thumbnail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.lazycat.apis.common.Thumbnail",
	HandlerType: (*ThumbnailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateFileThumbnail",
			Handler:    _Thumbnail_GenerateFileThumbnail_Handler,
		},
		{
			MethodName: "CleanAll",
			Handler:    _Thumbnail_CleanAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/media_meta.proto",
}
