// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.4
// source: sys/portal-server/portal-server.proto

package portal_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialerRole int32

const (
	DialerRole_GUEST_USER  DialerRole = 0 // 未登录也可以调用
	DialerRole_NORMAL_USER DialerRole = 1 // 登录的普通用户可以调用
	DialerRole_ADMIN_USER  DialerRole = 2 // 登录的管理员可以调用
)

// Enum value maps for DialerRole.
var (
	DialerRole_name = map[int32]string{
		0: "GUEST_USER",
		1: "NORMAL_USER",
		2: "ADMIN_USER",
	}
	DialerRole_value = map[string]int32{
		"GUEST_USER":  0,
		"NORMAL_USER": 1,
		"ADMIN_USER":  2,
	}
)

func (x DialerRole) Enum() *DialerRole {
	p := new(DialerRole)
	*p = x
	return p
}

func (x DialerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_portal_server_portal_server_proto_enumTypes[0].Descriptor()
}

func (DialerRole) Type() protoreflect.EnumType {
	return &file_sys_portal_server_portal_server_proto_enumTypes[0]
}

func (x DialerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialerRole.Descriptor instead.
func (DialerRole) EnumDescriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{0}
}

type Role int32

const (
	Role_NORMAL Role = 0
	Role_ADMIN  Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "NORMAL",
		1: "ADMIN",
	}
	Role_value = map[string]int32{
		"NORMAL": 0,
		"ADMIN":  1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_portal_server_portal_server_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_sys_portal_server_portal_server_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{1}
}

type RemoteSocksRequest_LocationType int32

const (
	RemoteSocksRequest_Unkonwn RemoteSocksRequest_LocationType = 0
	// 在当前hserver所处的物理网络协议栈上提供socks服务
	RemoteSocksRequest_Local RemoteSocksRequest_LocationType = 1
	// 在指定的的hclient所处的物理网络协议栈上提供socks服务
	RemoteSocksRequest_Remote RemoteSocksRequest_LocationType = 2
)

// Enum value maps for RemoteSocksRequest_LocationType.
var (
	RemoteSocksRequest_LocationType_name = map[int32]string{
		0: "Unkonwn",
		1: "Local",
		2: "Remote",
	}
	RemoteSocksRequest_LocationType_value = map[string]int32{
		"Unkonwn": 0,
		"Local":   1,
		"Remote":  2,
	}
)

func (x RemoteSocksRequest_LocationType) Enum() *RemoteSocksRequest_LocationType {
	p := new(RemoteSocksRequest_LocationType)
	*p = x
	return p
}

func (x RemoteSocksRequest_LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteSocksRequest_LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_portal_server_portal_server_proto_enumTypes[2].Descriptor()
}

func (RemoteSocksRequest_LocationType) Type() protoreflect.EnumType {
	return &file_sys_portal_server_portal_server_proto_enumTypes[2]
}

func (x RemoteSocksRequest_LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteSocksRequest_LocationType.Descriptor instead.
func (RemoteSocksRequest_LocationType) EnumDescriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{5, 0}
}

type ChangeTrustEndDeviceRequest_Action int32

const (
	ChangeTrustEndDeviceRequest_Add ChangeTrustEndDeviceRequest_Action = 0
	ChangeTrustEndDeviceRequest_Del ChangeTrustEndDeviceRequest_Action = 1
)

// Enum value maps for ChangeTrustEndDeviceRequest_Action.
var (
	ChangeTrustEndDeviceRequest_Action_name = map[int32]string{
		0: "Add",
		1: "Del",
	}
	ChangeTrustEndDeviceRequest_Action_value = map[string]int32{
		"Add": 0,
		"Del": 1,
	}
)

func (x ChangeTrustEndDeviceRequest_Action) Enum() *ChangeTrustEndDeviceRequest_Action {
	p := new(ChangeTrustEndDeviceRequest_Action)
	*p = x
	return p
}

func (x ChangeTrustEndDeviceRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeTrustEndDeviceRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_sys_portal_server_portal_server_proto_enumTypes[3].Descriptor()
}

func (ChangeTrustEndDeviceRequest_Action) Type() protoreflect.EnumType {
	return &file_sys_portal_server_portal_server_proto_enumTypes[3]
}

func (x ChangeTrustEndDeviceRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeTrustEndDeviceRequest_Action.Descriptor instead.
func (ChangeTrustEndDeviceRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{19, 0}
}

type RegisterBoxServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 服务名称，建议使用 xx.yy.zz.nn 这种形式
	// 如果此服务处于注册中，则后续请求会直接失败结束
	ServiceName    string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceNetwork string `protobuf:"bytes,2,opt,name=service_network,json=serviceNetwork,proto3" json:"service_network,omitempty"` //tcp、udp
	ServiceAddress string `protobuf:"bytes,3,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // $ip:$port
	// 服务提供的额外信息，此信息会原封不动的传递给hclient端，
	// service可以基于此机制进行进一步的安全认证等作用
	ExtraInfo string `protobuf:"bytes,6,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	// 需要调用者的身份
	RequireDialerRole DialerRole `protobuf:"varint,7,opt,name=require_dialer_role,json=requireDialerRole,proto3,enum=cloud.lazycat.apis.sys.DialerRole" json:"require_dialer_role,omitempty"`
	// 只有客户端是受信任设备时可以调用
	RequireTrustDev bool `protobuf:"varint,8,opt,name=require_trust_dev,json=requireTrustDev,proto3" json:"require_trust_dev,omitempty"`
}

func (x *RegisterBoxServiceRequest) Reset() {
	*x = RegisterBoxServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterBoxServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBoxServiceRequest) ProtoMessage() {}

func (x *RegisterBoxServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBoxServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterBoxServiceRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterBoxServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterBoxServiceRequest) GetServiceNetwork() string {
	if x != nil {
		return x.ServiceNetwork
	}
	return ""
}

func (x *RegisterBoxServiceRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *RegisterBoxServiceRequest) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

func (x *RegisterBoxServiceRequest) GetRequireDialerRole() DialerRole {
	if x != nil {
		return x.RequireDialerRole
	}
	return DialerRole_GUEST_USER
}

func (x *RegisterBoxServiceRequest) GetRequireTrustDev() bool {
	if x != nil {
		return x.RequireTrustDev
	}
	return false
}

type RegisterBoxServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterBoxServiceReply) Reset() {
	*x = RegisterBoxServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterBoxServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBoxServiceReply) ProtoMessage() {}

func (x *RegisterBoxServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBoxServiceReply.ProtoReflect.Descriptor instead.
func (*RegisterBoxServiceReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{1}
}

type EmitBoxServiceChangedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
}

func (x *EmitBoxServiceChangedRequest) Reset() {
	*x = EmitBoxServiceChangedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitBoxServiceChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitBoxServiceChangedRequest) ProtoMessage() {}

func (x *EmitBoxServiceChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitBoxServiceChangedRequest.ProtoReflect.Descriptor instead.
func (*EmitBoxServiceChangedRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{2}
}

func (x *EmitBoxServiceChangedRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type QueryBoxServicePeerCredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteAddr string `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	LocalAddr  string `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	Protocol   string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *QueryBoxServicePeerCredRequest) Reset() {
	*x = QueryBoxServicePeerCredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBoxServicePeerCredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBoxServicePeerCredRequest) ProtoMessage() {}

func (x *QueryBoxServicePeerCredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBoxServicePeerCredRequest.ProtoReflect.Descriptor instead.
func (*QueryBoxServicePeerCredRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{3}
}

func (x *QueryBoxServicePeerCredRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *QueryBoxServicePeerCredRequest) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *QueryBoxServicePeerCredRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type QueryBoxServicePeerCredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 若客户端未登录，则是SRP认证的UID，否则是登录的UID
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// string device_id = 2 [deprecated=true];
	DeviceVersion string `protobuf:"bytes,3,opt,name=device_version,json=deviceVersion,proto3" json:"device_version,omitempty"`
	VirtualIp     string `protobuf:"bytes,4,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	PeerId        string `protobuf:"bytes,5,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	IsLogined     bool   `protobuf:"varint,6,opt,name=is_logined,json=isLogined,proto3" json:"is_logined,omitempty"`
	IsTrustDev    bool   `protobuf:"varint,7,opt,name=is_trust_dev,json=isTrustDev,proto3" json:"is_trust_dev,omitempty"`
}

func (x *QueryBoxServicePeerCredResponse) Reset() {
	*x = QueryBoxServicePeerCredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBoxServicePeerCredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBoxServicePeerCredResponse) ProtoMessage() {}

func (x *QueryBoxServicePeerCredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBoxServicePeerCredResponse.ProtoReflect.Descriptor instead.
func (*QueryBoxServicePeerCredResponse) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{4}
}

func (x *QueryBoxServicePeerCredResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *QueryBoxServicePeerCredResponse) GetDeviceVersion() string {
	if x != nil {
		return x.DeviceVersion
	}
	return ""
}

func (x *QueryBoxServicePeerCredResponse) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *QueryBoxServicePeerCredResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *QueryBoxServicePeerCredResponse) GetIsLogined() bool {
	if x != nil {
		return x.IsLogined
	}
	return false
}

func (x *QueryBoxServicePeerCredResponse) GetIsTrustDev() bool {
	if x != nil {
		return x.IsTrustDev
	}
	return false
}

type RemoteSocksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocationType RemoteSocksRequest_LocationType `protobuf:"varint,1,opt,name=location_type,json=locationType,proto3,enum=cloud.lazycat.apis.sys.RemoteSocksRequest_LocationType" json:"location_type,omitempty"`
	Target       string                          `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // peer ID
}

func (x *RemoteSocksRequest) Reset() {
	*x = RemoteSocksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteSocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSocksRequest) ProtoMessage() {}

func (x *RemoteSocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSocksRequest.ProtoReflect.Descriptor instead.
func (*RemoteSocksRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteSocksRequest) GetLocationType() RemoteSocksRequest_LocationType {
	if x != nil {
		return x.LocationType
	}
	return RemoteSocksRequest_Unkonwn
}

func (x *RemoteSocksRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type RemoteSocksReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerUrl string `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` //返回的socks5服务器地址
}

func (x *RemoteSocksReply) Reset() {
	*x = RemoteSocksReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteSocksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteSocksReply) ProtoMessage() {}

func (x *RemoteSocksReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteSocksReply.ProtoReflect.Descriptor instead.
func (*RemoteSocksReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{6}
}

func (x *RemoteSocksReply) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

type ListUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uids []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersReply) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type HServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 中心化服务器地址, 默认为origin.lazycat.cloud
	OriginServer string `protobuf:"bytes,1,opt,name=origin_server,json=originServer,proto3" json:"origin_server,omitempty"`
	// fc03:1136:38/40地址
	VirtualIp string `protobuf:"bytes,2,opt,name=virtual_ip,json=virtualIp,proto3" json:"virtual_ip,omitempty"`
	// p2p节点id
	BoxId string `protobuf:"bytes,3,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	// 注册到origin-server内的名称
	BoxName string `protobuf:"bytes,4,opt,name=box_name,json=boxName,proto3" json:"box_name,omitempty"`
	// 从origin-server获取到的域名
	BoxDomain string `protobuf:"bytes,5,opt,name=box_domain,json=boxDomain,proto3" json:"box_domain,omitempty"`
}

func (x *HServerInfo) Reset() {
	*x = HServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HServerInfo) ProtoMessage() {}

func (x *HServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HServerInfo.ProtoReflect.Descriptor instead.
func (*HServerInfo) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{8}
}

func (x *HServerInfo) GetOriginServer() string {
	if x != nil {
		return x.OriginServer
	}
	return ""
}

func (x *HServerInfo) GetVirtualIp() string {
	if x != nil {
		return x.VirtualIp
	}
	return ""
}

func (x *HServerInfo) GetBoxId() string {
	if x != nil {
		return x.BoxId
	}
	return ""
}

func (x *HServerInfo) GetBoxName() string {
	if x != nil {
		return x.BoxName
	}
	return ""
}

func (x *HServerInfo) GetBoxDomain() string {
	if x != nil {
		return x.BoxDomain
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// 此设备当前是否连接到盒子
	IsOnline bool `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	// 设备绑定时间
	BindingTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=binding_time,json=bindingTime,proto3" json:"binding_time,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{9}
}

func (x *Device) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Device) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *Device) GetBindingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BindingTime
	}
	return nil
}

type ListEndDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ListEndDeviceRequest) Reset() {
	*x = ListEndDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndDeviceRequest) ProtoMessage() {}

func (x *ListEndDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndDeviceRequest.ProtoReflect.Descriptor instead.
func (*ListEndDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{10}
}

func (x *ListEndDeviceRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ListEndDeviceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *ListEndDeviceReply) Reset() {
	*x = ListEndDeviceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndDeviceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndDeviceReply) ProtoMessage() {}

func (x *ListEndDeviceReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndDeviceReply.ProtoReflect.Descriptor instead.
func (*ListEndDeviceReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{11}
}

func (x *ListEndDeviceReply) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserID) Reset() {
	*x = UserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{12}
}

func (x *UserID) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ChangeRoleReqeust struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role Role   `protobuf:"varint,2,opt,name=role,proto3,enum=cloud.lazycat.apis.sys.Role" json:"role,omitempty"`
}

func (x *ChangeRoleReqeust) Reset() {
	*x = ChangeRoleReqeust{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRoleReqeust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoleReqeust) ProtoMessage() {}

func (x *ChangeRoleReqeust) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoleReqeust.ProtoReflect.Descriptor instead.
func (*ChangeRoleReqeust) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeRoleReqeust) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeRoleReqeust) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NORMAL
}

type QueryRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role Role   `protobuf:"varint,2,opt,name=role,proto3,enum=cloud.lazycat.apis.sys.Role" json:"role,omitempty"`
}

func (x *QueryRoleReply) Reset() {
	*x = QueryRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoleReply) ProtoMessage() {}

func (x *QueryRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoleReply.ProtoReflect.Descriptor instead.
func (*QueryRoleReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{14}
}

func (x *QueryRoleReply) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *QueryRoleReply) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NORMAL
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{15}
}

func (x *ResetPasswordRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role     Role   `protobuf:"varint,3,opt,name=role,proto3,enum=cloud.lazycat.apis.sys.Role" json:"role,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{17}
}

func (x *CreateUserRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NORMAL
}

type CheckPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CheckPasswordRequest) Reset() {
	*x = CheckPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPasswordRequest) ProtoMessage() {}

func (x *CheckPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPasswordRequest.ProtoReflect.Descriptor instead.
func (*CheckPasswordRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{18}
}

func (x *CheckPasswordRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CheckPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ChangeTrustEndDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string                             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cid    string                             `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"` // peer ID
	Action ChangeTrustEndDeviceRequest_Action `protobuf:"varint,3,opt,name=action,proto3,enum=cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest_Action" json:"action,omitempty"`
}

func (x *ChangeTrustEndDeviceRequest) Reset() {
	*x = ChangeTrustEndDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTrustEndDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTrustEndDeviceRequest) ProtoMessage() {}

func (x *ChangeTrustEndDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTrustEndDeviceRequest.ProtoReflect.Descriptor instead.
func (*ChangeTrustEndDeviceRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{19}
}

func (x *ChangeTrustEndDeviceRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChangeTrustEndDeviceRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ChangeTrustEndDeviceRequest) GetAction() ChangeTrustEndDeviceRequest_Action {
	if x != nil {
		return x.Action
	}
	return ChangeTrustEndDeviceRequest_Add
}

type ChangeTrustEndDeviceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeTrustEndDeviceReply) Reset() {
	*x = ChangeTrustEndDeviceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTrustEndDeviceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTrustEndDeviceReply) ProtoMessage() {}

func (x *ChangeTrustEndDeviceReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTrustEndDeviceReply.ProtoReflect.Descriptor instead.
func (*ChangeTrustEndDeviceReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{20}
}

type SetupHServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginServer string `protobuf:"bytes,1,opt,name=origin_server,json=originServer,proto3" json:"origin_server,omitempty"`
	BoxName      string `protobuf:"bytes,2,opt,name=box_name,json=boxName,proto3" json:"box_name,omitempty"`
	Username     string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password     string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SetupHServerRequest) Reset() {
	*x = SetupHServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupHServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupHServerRequest) ProtoMessage() {}

func (x *SetupHServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupHServerRequest.ProtoReflect.Descriptor instead.
func (*SetupHServerRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{21}
}

func (x *SetupHServerRequest) GetOriginServer() string {
	if x != nil {
		return x.OriginServer
	}
	return ""
}

func (x *SetupHServerRequest) GetBoxName() string {
	if x != nil {
		return x.BoxName
	}
	return ""
}

func (x *SetupHServerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetupHServerRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SetupHServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *SetupHServerReply) Reset() {
	*x = SetupHServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupHServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupHServerReply) ProtoMessage() {}

func (x *SetupHServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupHServerReply.ProtoReflect.Descriptor instead.
func (*SetupHServerReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{22}
}

func (x *SetupHServerReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetupHServerReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResetHServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginServer string `protobuf:"bytes,1,opt,name=origin_server,json=originServer,proto3" json:"origin_server,omitempty"`
}

func (x *ResetHServerRequest) Reset() {
	*x = ResetHServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetHServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHServerRequest) ProtoMessage() {}

func (x *ResetHServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHServerRequest.ProtoReflect.Descriptor instead.
func (*ResetHServerRequest) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{23}
}

func (x *ResetHServerRequest) GetOriginServer() string {
	if x != nil {
		return x.OriginServer
	}
	return ""
}

type ResetHServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetHServerReply) Reset() {
	*x = ResetHServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_portal_server_portal_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetHServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHServerReply) ProtoMessage() {}

func (x *ResetHServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_sys_portal_server_portal_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHServerReply.ProtoReflect.Descriptor instead.
func (*ResetHServerReply) Descriptor() ([]byte, []int) {
	return file_sys_portal_server_portal_server_proto_rawDescGZIP(), []int{24}
}

var File_sys_portal_server_portal_server_proto protoreflect.FileDescriptor

var file_sys_portal_server_portal_server_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x79, 0x73, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c,
	0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x02,
	0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x52, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x64, 0x69, 0x61, 0x6c, 0x65,
	0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x11, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x5f, 0x74,
	0x72, 0x75, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x76, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x44, 0x65, 0x76, 0x22,
	0x19, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x41, 0x0a, 0x1c, 0x45, 0x6d,
	0x69, 0x74, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a,
	0x1e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x65, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xd3, 0x01, 0x0a, 0x1f,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x65, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x49, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x76, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x54, 0x72, 0x75, 0x73, 0x74, 0x44, 0x65,
	0x76, 0x22, 0xbe, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5c, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x37, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53,
	0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x32,
	0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6f, 0x6e, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x10, 0x02, 0x22, 0x31, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0b,
	0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x49, 0x70, 0x12,
	0x15, 0x0a, 0x06, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x78, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x78, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x7d, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x3d, 0x0a, 0x0c, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x28, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x38, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x1a, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x73, 0x79, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x54,
	0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x22, 0x51, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x73,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x1b, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x52, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75,
	0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10, 0x01, 0x22, 0x1b, 0x0a,
	0x19, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x13, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x78, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3b, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x75, 0x70, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x3a, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x65, 0x74, 0x48, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x3d, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x6c,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x4d, 0x49, 0x4e,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x1d, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x32, 0xc8, 0x0c, 0x0a, 0x0a, 0x48, 0x50, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x53, 0x79, 0x73, 0x12, 0x51, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x23, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x48, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x26, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x29, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61,
	0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x29, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79,
	0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x57, 0x0a,
	0x0d, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2c,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2c, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x26, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x29, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a,
	0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x65, 0x75, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x80, 0x01, 0x0a, 0x14, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x33, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63,
	0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2c,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x0b, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x2a, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73,
	0x79, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61,
	0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x66, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x75, 0x70, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x2b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x48, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73,
	0x79, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c,
	0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x48, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x7a, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x73, 0x79, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30, 0x01, 0x12, 0x65, 0x0a,
	0x15, 0x45, 0x6d, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x34, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c,
	0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e,
	0x45, 0x6d, 0x69, 0x74, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x8a, 0x01, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6f,
	0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x65, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64,
	0x12, 0x36, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42,
	0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x65, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x6c, 0x61, 0x7a, 0x79, 0x63, 0x61, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x73, 0x79,
	0x73, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x65, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x69, 0x2f, 0x6c, 0x7a, 0x63, 0x2d, 0x73, 0x64, 0x6b, 0x2f,
	0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x79, 0x73, 0x2f, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_sys_portal_server_portal_server_proto_rawDescOnce sync.Once
	file_sys_portal_server_portal_server_proto_rawDescData = file_sys_portal_server_portal_server_proto_rawDesc
)

func file_sys_portal_server_portal_server_proto_rawDescGZIP() []byte {
	file_sys_portal_server_portal_server_proto_rawDescOnce.Do(func() {
		file_sys_portal_server_portal_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_portal_server_portal_server_proto_rawDescData)
	})
	return file_sys_portal_server_portal_server_proto_rawDescData
}

var file_sys_portal_server_portal_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sys_portal_server_portal_server_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_sys_portal_server_portal_server_proto_goTypes = []interface{}{
	(DialerRole)(0),                         // 0: cloud.lazycat.apis.sys.DialerRole
	(Role)(0),                               // 1: cloud.lazycat.apis.sys.Role
	(RemoteSocksRequest_LocationType)(0),    // 2: cloud.lazycat.apis.sys.RemoteSocksRequest.LocationType
	(ChangeTrustEndDeviceRequest_Action)(0), // 3: cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest.Action
	(*RegisterBoxServiceRequest)(nil),       // 4: cloud.lazycat.apis.sys.RegisterBoxServiceRequest
	(*RegisterBoxServiceReply)(nil),         // 5: cloud.lazycat.apis.sys.RegisterBoxServiceReply
	(*EmitBoxServiceChangedRequest)(nil),    // 6: cloud.lazycat.apis.sys.EmitBoxServiceChangedRequest
	(*QueryBoxServicePeerCredRequest)(nil),  // 7: cloud.lazycat.apis.sys.QueryBoxServicePeerCredRequest
	(*QueryBoxServicePeerCredResponse)(nil), // 8: cloud.lazycat.apis.sys.QueryBoxServicePeerCredResponse
	(*RemoteSocksRequest)(nil),              // 9: cloud.lazycat.apis.sys.RemoteSocksRequest
	(*RemoteSocksReply)(nil),                // 10: cloud.lazycat.apis.sys.RemoteSocksReply
	(*ListUsersReply)(nil),                  // 11: cloud.lazycat.apis.sys.ListUsersReply
	(*HServerInfo)(nil),                     // 12: cloud.lazycat.apis.sys.HServerInfo
	(*Device)(nil),                          // 13: cloud.lazycat.apis.sys.Device
	(*ListEndDeviceRequest)(nil),            // 14: cloud.lazycat.apis.sys.ListEndDeviceRequest
	(*ListEndDeviceReply)(nil),              // 15: cloud.lazycat.apis.sys.ListEndDeviceReply
	(*UserID)(nil),                          // 16: cloud.lazycat.apis.sys.UserID
	(*ChangeRoleReqeust)(nil),               // 17: cloud.lazycat.apis.sys.ChangeRoleReqeust
	(*QueryRoleReply)(nil),                  // 18: cloud.lazycat.apis.sys.QueryRoleReply
	(*ResetPasswordRequest)(nil),            // 19: cloud.lazycat.apis.sys.ResetPasswordRequest
	(*DeleteUserRequest)(nil),               // 20: cloud.lazycat.apis.sys.DeleteUserRequest
	(*CreateUserRequest)(nil),               // 21: cloud.lazycat.apis.sys.CreateUserRequest
	(*CheckPasswordRequest)(nil),            // 22: cloud.lazycat.apis.sys.CheckPasswordRequest
	(*ChangeTrustEndDeviceRequest)(nil),     // 23: cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest
	(*ChangeTrustEndDeviceReply)(nil),       // 24: cloud.lazycat.apis.sys.ChangeTrustEndDeviceReply
	(*SetupHServerRequest)(nil),             // 25: cloud.lazycat.apis.sys.SetupHServerRequest
	(*SetupHServerReply)(nil),               // 26: cloud.lazycat.apis.sys.SetupHServerReply
	(*ResetHServerRequest)(nil),             // 27: cloud.lazycat.apis.sys.ResetHServerRequest
	(*ResetHServerReply)(nil),               // 28: cloud.lazycat.apis.sys.ResetHServerReply
	(*timestamppb.Timestamp)(nil),           // 29: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 30: google.protobuf.Empty
}
var file_sys_portal_server_portal_server_proto_depIdxs = []int32{
	0,  // 0: cloud.lazycat.apis.sys.RegisterBoxServiceRequest.require_dialer_role:type_name -> cloud.lazycat.apis.sys.DialerRole
	2,  // 1: cloud.lazycat.apis.sys.RemoteSocksRequest.location_type:type_name -> cloud.lazycat.apis.sys.RemoteSocksRequest.LocationType
	29, // 2: cloud.lazycat.apis.sys.Device.binding_time:type_name -> google.protobuf.Timestamp
	13, // 3: cloud.lazycat.apis.sys.ListEndDeviceReply.devices:type_name -> cloud.lazycat.apis.sys.Device
	1,  // 4: cloud.lazycat.apis.sys.ChangeRoleReqeust.role:type_name -> cloud.lazycat.apis.sys.Role
	1,  // 5: cloud.lazycat.apis.sys.QueryRoleReply.role:type_name -> cloud.lazycat.apis.sys.Role
	1,  // 6: cloud.lazycat.apis.sys.CreateUserRequest.role:type_name -> cloud.lazycat.apis.sys.Role
	3,  // 7: cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest.action:type_name -> cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest.Action
	30, // 8: cloud.lazycat.apis.sys.HPortalSys.QueryHServerInfo:input_type -> google.protobuf.Empty
	30, // 9: cloud.lazycat.apis.sys.HPortalSys.ListUsers:input_type -> google.protobuf.Empty
	21, // 10: cloud.lazycat.apis.sys.HPortalSys.CreateUser:input_type -> cloud.lazycat.apis.sys.CreateUserRequest
	20, // 11: cloud.lazycat.apis.sys.HPortalSys.DeleteUser:input_type -> cloud.lazycat.apis.sys.DeleteUserRequest
	19, // 12: cloud.lazycat.apis.sys.HPortalSys.ResetPassword:input_type -> cloud.lazycat.apis.sys.ResetPasswordRequest
	22, // 13: cloud.lazycat.apis.sys.HPortalSys.CheckPassword:input_type -> cloud.lazycat.apis.sys.CheckPasswordRequest
	16, // 14: cloud.lazycat.apis.sys.HPortalSys.QueryRole:input_type -> cloud.lazycat.apis.sys.UserID
	17, // 15: cloud.lazycat.apis.sys.HPortalSys.ChangeRole:input_type -> cloud.lazycat.apis.sys.ChangeRoleReqeust
	23, // 16: cloud.lazycat.apis.sys.HPortalSys.ChangeTrustEndDevice:input_type -> cloud.lazycat.apis.sys.ChangeTrustEndDeviceRequest
	14, // 17: cloud.lazycat.apis.sys.HPortalSys.ListEndDevices:input_type -> cloud.lazycat.apis.sys.ListEndDeviceRequest
	9,  // 18: cloud.lazycat.apis.sys.HPortalSys.RemoteSocks:input_type -> cloud.lazycat.apis.sys.RemoteSocksRequest
	25, // 19: cloud.lazycat.apis.sys.HPortalSys.SetupHServer:input_type -> cloud.lazycat.apis.sys.SetupHServerRequest
	27, // 20: cloud.lazycat.apis.sys.HPortalSys.ResetHServer:input_type -> cloud.lazycat.apis.sys.ResetHServerRequest
	4,  // 21: cloud.lazycat.apis.sys.HPortalSys.RegisterBoxService:input_type -> cloud.lazycat.apis.sys.RegisterBoxServiceRequest
	6,  // 22: cloud.lazycat.apis.sys.HPortalSys.EmitBoxServiceChanged:input_type -> cloud.lazycat.apis.sys.EmitBoxServiceChangedRequest
	7,  // 23: cloud.lazycat.apis.sys.HPortalSys.QueryBoxServicePeerCred:input_type -> cloud.lazycat.apis.sys.QueryBoxServicePeerCredRequest
	12, // 24: cloud.lazycat.apis.sys.HPortalSys.QueryHServerInfo:output_type -> cloud.lazycat.apis.sys.HServerInfo
	11, // 25: cloud.lazycat.apis.sys.HPortalSys.ListUsers:output_type -> cloud.lazycat.apis.sys.ListUsersReply
	30, // 26: cloud.lazycat.apis.sys.HPortalSys.CreateUser:output_type -> google.protobuf.Empty
	30, // 27: cloud.lazycat.apis.sys.HPortalSys.DeleteUser:output_type -> google.protobuf.Empty
	30, // 28: cloud.lazycat.apis.sys.HPortalSys.ResetPassword:output_type -> google.protobuf.Empty
	30, // 29: cloud.lazycat.apis.sys.HPortalSys.CheckPassword:output_type -> google.protobuf.Empty
	18, // 30: cloud.lazycat.apis.sys.HPortalSys.QueryRole:output_type -> cloud.lazycat.apis.sys.QueryRoleReply
	30, // 31: cloud.lazycat.apis.sys.HPortalSys.ChangeRole:output_type -> google.protobuf.Empty
	24, // 32: cloud.lazycat.apis.sys.HPortalSys.ChangeTrustEndDevice:output_type -> cloud.lazycat.apis.sys.ChangeTrustEndDeviceReply
	15, // 33: cloud.lazycat.apis.sys.HPortalSys.ListEndDevices:output_type -> cloud.lazycat.apis.sys.ListEndDeviceReply
	10, // 34: cloud.lazycat.apis.sys.HPortalSys.RemoteSocks:output_type -> cloud.lazycat.apis.sys.RemoteSocksReply
	26, // 35: cloud.lazycat.apis.sys.HPortalSys.SetupHServer:output_type -> cloud.lazycat.apis.sys.SetupHServerReply
	28, // 36: cloud.lazycat.apis.sys.HPortalSys.ResetHServer:output_type -> cloud.lazycat.apis.sys.ResetHServerReply
	5,  // 37: cloud.lazycat.apis.sys.HPortalSys.RegisterBoxService:output_type -> cloud.lazycat.apis.sys.RegisterBoxServiceReply
	30, // 38: cloud.lazycat.apis.sys.HPortalSys.EmitBoxServiceChanged:output_type -> google.protobuf.Empty
	8,  // 39: cloud.lazycat.apis.sys.HPortalSys.QueryBoxServicePeerCred:output_type -> cloud.lazycat.apis.sys.QueryBoxServicePeerCredResponse
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sys_portal_server_portal_server_proto_init() }
func file_sys_portal_server_portal_server_proto_init() {
	if File_sys_portal_server_portal_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_portal_server_portal_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterBoxServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterBoxServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitBoxServiceChangedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBoxServicePeerCredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBoxServicePeerCredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteSocksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteSocksReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndDeviceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRoleReqeust); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTrustEndDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTrustEndDeviceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupHServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupHServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetHServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_portal_server_portal_server_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetHServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_portal_server_portal_server_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_portal_server_portal_server_proto_goTypes,
		DependencyIndexes: file_sys_portal_server_portal_server_proto_depIdxs,
		EnumInfos:         file_sys_portal_server_portal_server_proto_enumTypes,
		MessageInfos:      file_sys_portal_server_portal_server_proto_msgTypes,
	}.Build()
	File_sys_portal_server_portal_server_proto = out.File
	file_sys_portal_server_portal_server_proto_rawDesc = nil
	file_sys_portal_server_portal_server_proto_goTypes = nil
	file_sys_portal_server_portal_server_proto_depIdxs = nil
}
